# Generated by Django 4.1 on 2024-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AWLT", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(db_column="FirstName", max_length=50)),
                ("LastName", models.CharField(db_column="LastName", max_length=50)),
            ],
            options={
                "db_table": "Customer",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
    ]
