# Generated by Django 4.1 on 2024-03-15 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientTable",
            fields=[
                (
                    "ClientID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("CompanyName", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=60)),
                ("City", models.CharField(max_length=60)),
                ("Zip", models.IntegerField()),
                ("Phone", models.CharField(blank=True, max_length=45)),
                ("ModifiedDate", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "Client",
            },
        ),
        migrations.CreateModel(
            name="ContactTable",
            fields=[
                ("ContactID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(blank=True, max_length=8, null=True)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("Email", models.CharField(blank=True, max_length=50, null=True)),
                ("Phone", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "VeslContact",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("passwordhash", models.CharField(max_length=128)),
                ("passwordsalt", models.CharField(max_length=10)),
                ("ModifiedDate", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.clienttable",
                    ),
                ),
            ],
            options={
                "db_table": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="ServicesTable",
            fields=[
                ("ServiceID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ServiceType",
                    models.CharField(
                        choices=[
                            ("24-7", "Twenty-Four Seven"),
                            ("PS", "Partial Service"),
                            ("1T", "One Time Service"),
                        ],
                        max_length=4,
                    ),
                ),
                ("ModifiedDate", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.clienttable",
                    ),
                ),
            ],
            options={
                "db_table": "Services",
            },
        ),
        migrations.CreateModel(
            name="FacilityTable",
            fields=[
                ("FacilityID", models.AutoField(primary_key=True, serialize=False)),
                ("FacilityName", models.CharField(max_length=100)),
                (
                    "FacilityType",
                    models.CharField(
                        choices=[
                            ("A", "Food"),
                            ("B", "Chemical"),
                            ("C", "Textile"),
                            ("D", "Web-Converting"),
                        ],
                        max_length=1,
                    ),
                ),
                ("Address", models.CharField(max_length=60)),
                ("City", models.CharField(max_length=60)),
                ("Zip", models.IntegerField()),
                ("Phone", models.CharField(blank=True, max_length=45)),
                ("ModifiedDate", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.clienttable",
                    ),
                ),
                (
                    "Contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.contacttable",
                    ),
                ),
            ],
            options={
                "db_table": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="EquipmentTable",
            fields=[
                ("EquipmentID", models.AutoField(primary_key=True, serialize=False)),
                ("EquipmentName", models.CharField(max_length=50)),
                ("SerialNum", models.IntegerField()),
                ("IoT", models.BooleanField()),
                ("IoTAddress", models.CharField(max_length=120)),
                ("Modeled", models.BooleanField()),
                ("ModifiedDate", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.clienttable",
                    ),
                ),
                (
                    "Facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClientApp.facilitytable",
                    ),
                ),
            ],
            options={
                "db_table": "Equipment",
            },
        ),
    ]
