# Generated by Django 4.1 on 2024-03-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ClientApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttable",
            name="State",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
