# Generated by Django 4.1 on 2024-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ClientApp", "0002_clienttable_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienttable",
            name="State",
            field=models.CharField(default="Colorado", max_length=25),
            preserve_default=False,
        ),
    ]
