# Generated by Django 4.1 on 2024-03-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ClientApp", "0003_alter_clienttable_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicestable",
            name="Client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Services",
                to="ClientApp.clienttable",
            ),
        ),
    ]
