# Generated by Django 4.1 on 2024-03-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ClientApp", "0004_alter_servicestable_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacttable",
            old_name="VeslContact",
            new_name="VESLContact",
        ),
        migrations.RemoveField(
            model_name="facilitytable",
            name="Contact",
        ),
        migrations.AddField(
            model_name="contacttable",
            name="ClientPrimary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contacttable",
            name="Facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ClientApp.facilitytable",
            ),
        ),
        migrations.AddField(
            model_name="contacttable",
            name="FacilityPrimary",
            field=models.BooleanField(default=False),
        ),
    ]
