# Generated by Django 4.1 on 2024-03-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ClientApp", "0007_alter_contacttable_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttable",
            name="Client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Contacts",
                to="ClientApp.clienttable",
            ),
        ),
        migrations.AlterField(
            model_name="contacttable",
            name="Facility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Contacts",
                to="ClientApp.facilitytable",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttable",
            name="Client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Equipment",
                to="ClientApp.clienttable",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttable",
            name="Facility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Equipment",
                to="ClientApp.facilitytable",
            ),
        ),
        migrations.AlterField(
            model_name="facilitytable",
            name="Client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Facilities",
                to="ClientApp.clienttable",
            ),
        ),
        migrations.AlterField(
            model_name="servicestable",
            name="Client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Services",
                to="ClientApp.clienttable",
            ),
        ),
    ]
